### ISSUE TITLE
Add `py.typed` file

### ISSUE THREAD

**Issue by LightArrowsEXE** [OpusGang/rekt#3]
Currently, mypy will always complain about missing stubs.

![image](https://user-images.githubusercontent.com/42927908/220039968-7c2e5e7a-115b-4d73-9be6-ce18c14cf621.png)

It'd be nice if there were a `py.typed` file to tell it to shush, and so users do not have to generate their own stubs.

This also extends to other packages, and I see `awsmfunc` already has one.

**Comment by quietvoid** [comment]
Sure, will add.
Currently nothing is typed either, so I assumed it wasn't necessary.

**Comment by LightArrowsEXE** [comment]
It really just keeps mypy from complaining. Might be a good opportunity to type it now before a new release gets pushed, perhaps?

**Comment by quietvoid** [comment]
That is indeed the plan.
